import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author soham
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Admin = new javax.swing.JButton();
        jButton_Student = new javax.swing.JButton();
        jButton_Close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        setMinimumSize(new java.awt.Dimension(959, 540));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Admin.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jButton_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/index admin.png"))); // NOI18N
        jButton_Admin.setText("Admin");
        jButton_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdminActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 140, -1));

        jButton_Student.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jButton_Student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/index student.png"))); // NOI18N
        jButton_Student.setText("Student");
        jButton_Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StudentActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jButton_Close.setBackground(new java.awt.Color(255, 0, 0));
        jButton_Close.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton_Close.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Close.setText("X");
        jButton_Close.setAlignmentY(0.0F);
        jButton_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CloseActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 60, 60));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel1.setText("Login as:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StudentActionPerformed
        dispose();
        new studentDetails().setVisible(true);
    }//GEN-LAST:event_jButton_StudentActionPerformed

    private void jButton_AdminActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        new loginAdmin().setVisible(true);
        jButton_Close.setVisible(false);
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton_CloseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do You Really want to Exit the application?", "Select",
                JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }// GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Admin;
    private javax.swing.JButton jButton_Close;
    private javax.swing.JButton jButton_Student;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
