/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

import java.sql.*;
import Project.ConnectionProvider;

/**
 *
 * @author soham
 */
public class studentDetails extends javax.swing.JFrame {

    /**
     * Creates new form studentDetails
     */
    public studentDetails() {
        initComponents();
        jTextArea_Rules.setEditable(false);
        jTextArea_Instructions.setEditable(false);
        SimpleDateFormat dFormat = new SimpleDateFormat("dd:MM:yyyy");
        Date date = new Date();
        jLabel_ShowDate.setText(dFormat.format(date));
        jTextField_Roll.setText("Enter your full roll number");
        jTextField_FirstName.setText("Enter your first name");
        jTextField_LastName.setText("Enter your last name");
        jTextField_Phone.setText("Enter your phone number");
        jTextField_Email.setText("Enter your email address");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel_StudentDetails = new javax.swing.JLabel();
        jButton_Close = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jRoll = new javax.swing.JLabel();
        jName = new javax.swing.JLabel();
        jGender = new javax.swing.JLabel();
        jPhone = new javax.swing.JLabel();
        jEmail = new javax.swing.JLabel();
        jTextField_Roll = new javax.swing.JTextField();
        jTextField_Phone = new javax.swing.JTextField();
        jTextField_FirstName = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jButton_Save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_LastName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Instructions = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Rules = new javax.swing.JTextArea();
        jLabel_Date = new javax.swing.JLabel();
        jLabel_ShowDate = new javax.swing.JLabel();
        jButton_Search = new javax.swing.JButton();
        jButton_Proceed = new javax.swing.JButton();
        jComboBox_Gender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(959, 546));
        setMinimumSize(new java.awt.Dimension(959, 546));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(959, 546));
        setResizable(false);

        jLabel_StudentDetails.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_StudentDetails.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel_StudentDetails.setText("Student Details");

        jButton_Close.setBackground(new java.awt.Color(255, 0, 0));
        jButton_Close.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton_Close.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Close.setText("Back");
        jButton_Close.setBorder(null);
        jButton_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CloseActionPerformed(evt);
            }
        });

        jRoll.setBackground(new java.awt.Color(0, 0, 0));
        jRoll.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRoll.setText("Roll:");

        jName.setBackground(new java.awt.Color(0, 0, 0));
        jName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jName.setText("First Name:");

        jGender.setBackground(new java.awt.Color(0, 0, 0));
        jGender.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jGender.setText("Gender:");

        jPhone.setBackground(new java.awt.Color(0, 0, 0));
        jPhone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPhone.setText("Phone:");

        jEmail.setBackground(new java.awt.Color(0, 0, 0));
        jEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jEmail.setText("Email:");

        jTextField_Roll.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_RollFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_RollFocusLost(evt);
            }
        });

        jTextField_Phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_PhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_PhoneFocusLost(evt);
            }
        });

        jTextField_FirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_FirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_FirstNameFocusLost(evt);
            }
        });

        jTextField_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_EmailFocusLost(evt);
            }
        });

        jButton_Save.setBackground(new java.awt.Color(153, 204, 255));
        jButton_Save.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton_Save.setText("Save & Proceed");
        jButton_Save.setBorder(null);
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Last Name:");

        jTextField_LastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_LastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_LastNameFocusLost(evt);
            }
        });

        jTextArea_Instructions.setColumns(20);
        jTextArea_Instructions.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Instructions);

        jTextArea_Rules.setColumns(20);
        jTextArea_Rules.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Rules);

        jLabel_Date.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_Date.setText("Date:");

        jLabel_ShowDate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel_ShowDate.setText("Show_Date");

        jButton_Search.setBackground(new java.awt.Color(0, 255, 0));
        jButton_Search.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_Search.setText("Search");
        jButton_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_SearchMouseClicked(evt);
            }
        });

        jButton_Proceed.setBackground(new java.awt.Color(51, 102, 255));
        jButton_Proceed.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton_Proceed.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Proceed.setText("Proceed");
        jButton_Proceed.setBorder(null);
        jButton_Proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProceedActionPerformed(evt);
            }
        });

        jComboBox_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_StudentDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_ShowDate))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jPhone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jName)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_FirstName))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jGender)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBox_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRoll)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField_Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jEmail))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                            .addComponent(jTextField_LastName)))
                                    .addComponent(jButton_Search)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jButton_Proceed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_StudentDetails)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_ShowDate)
                        .addComponent(jLabel_Date)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Search)
                            .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPhone))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jName)
                            .addComponent(jTextField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jGender)
                            .addComponent(jComboBox_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEmail)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRoll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Roll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Proceed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SearchMouseClicked
        String phone = jTextField_Phone.getText();
        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("select * from student where phone = ?");
            ps.setString(1, phone);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                jButton_Save.setEnabled(false);
                jTextField_FirstName.setText(rs.getString(2));
                jTextField_LastName.setText(rs.getString(3));
                jTextField_Roll.setText(rs.getString(1));
                jTextField_Email.setText(rs.getString(6));
                jComboBox_Gender.setSelectedItem(rs.getString(4));
                jTextField_FirstName.setEditable(false);
                jTextField_LastName.setEditable(false);
                jTextField_Phone.setEditable(false);
                jTextField_Email.setEditable(false);
            } else {
                jTextField_FirstName.setEditable(true);
                jTextField_LastName.setEditable(true);
                jTextField_Phone.setEditable(true);
                jTextField_Email.setEditable(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton_SearchMouseClicked

    private void jButton_ProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProceedActionPerformed
        jButton_Save.setEnabled(true);
        String phone = jTextField_Phone.getText();
        new quizExamStudent(phone).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton_ProceedActionPerformed

    private void jButton_CloseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_CloseActionPerformed
        new index().setVisible(true);
        dispose();
    }// GEN-LAST:event_jButton_CloseActionPerformed

    private void jTextField_RollFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_RollFocusGained
        if (jTextField_Roll.getText().equals("Enter your full roll number")) {
            jTextField_Roll.setText("");
        }
    }// GEN-LAST:event_jTextField_RollFocusGained

    private void jTextField_FirstNameFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_FirstNameFocusGained
        if (jTextField_FirstName.getText().equals("Enter your first name")) {
            jTextField_FirstName.setText("");
        }
    }// GEN-LAST:event_jTextField_FirstNameFocusGained

    private void jTextField_LastNameFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_LastNameFocusGained
        if (jTextField_LastName.getText().equals("Enter your last name")) {
            jTextField_LastName.setText("");
        }
    }// GEN-LAST:event_jTextField_LastNameFocusGained

    private void jTextField_PhoneFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_PhoneFocusGained
        if (jTextField_Phone.getText().equals("Enter your phone number")) {
            jTextField_Phone.setText("");
        }
    }// GEN-LAST:event_jTextField_PhoneFocusGained

    private void jTextField_EmailFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_EmailFocusGained
        if (jTextField_Email.getText().equals("Enter your email address")) {
            jTextField_Email.setText("");
        }
    }// GEN-LAST:event_jTextField_EmailFocusGained

    private void jTextField_RollFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_RollFocusLost
        if (jTextField_Roll.getText().equals("")) {
            jTextField_Roll.setText("Enter your full roll number");
        }
    }// GEN-LAST:event_jTextField_RollFocusLost

    private void jTextField_FirstNameFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_FirstNameFocusLost
        if (jTextField_FirstName.getText().equals("")) {
            jTextField_FirstName.setText("Enter your first name");
        }
    }// GEN-LAST:event_jTextField_FirstNameFocusLost

    private void jTextField_LastNameFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_LastNameFocusLost
        if (jTextField_LastName.getText().equals("")) {
            jTextField_LastName.setText("Enter your last name");
        }
    }// GEN-LAST:event_jTextField_LastNameFocusLost

    private void jTextField_PhoneFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_PhoneFocusLost
        if (jTextField_Phone.getText().equals("")) {
            jTextField_Phone.setText("Enter your phone number");
        }
    }// GEN-LAST:event_jTextField_PhoneFocusLost

    private void jTextField_EmailFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_EmailFocusLost
        if (jTextField_Email.getText().equals("")) {
            jTextField_Email.setText("Enter your email address");
        }
    }// GEN-LAST:event_jTextField_EmailFocusLost

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {
        String roll = jTextField_Roll.getText();
        String firstname = jTextField_FirstName.getText();
        String lastname = jTextField_LastName.getText();
        String gender = (String) jComboBox_Gender.getSelectedItem();

        String phone = jTextField_Phone.getText();
        String email = jTextField_Email.getText();
        String marks = "0";

        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement checkStmt = con.prepareStatement("SELECT COUNT(*) FROM student WHERE phone = ? OR email = ?");
            checkStmt.setString(1, phone);
            checkStmt.setString(2, email);
            ResultSet rs = checkStmt.executeQuery();
            rs.next();
            if (rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(null,
                        "Phone number or email already exists. Please enter another.");
            } else {
                PreparedStatement ps = con.prepareStatement("insert into student values(?,?,?,?,?,?,?)");
                ps.setString(1, roll);
                ps.setString(2, firstname);
                ps.setString(3, lastname);
                ps.setString(4, gender);
                ps.setString(5, phone);
                ps.setString(6, email);
                ps.setString(7, marks);
                ps.executeUpdate();

                new quizExamStudent(phone).setVisible(true);
                setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }// GEN-LAST:event_jButton_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Close;
    private javax.swing.JButton jButton_Proceed;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JComboBox<String> jComboBox_Gender;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JLabel jLabel_ShowDate;
    private javax.swing.JLabel jLabel_StudentDetails;
    private javax.swing.JLabel jName;
    private javax.swing.JLabel jPhone;
    private javax.swing.JLabel jRoll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea_Instructions;
    private javax.swing.JTextArea jTextArea_Rules;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_FirstName;
    private javax.swing.JTextField jTextField_LastName;
    private javax.swing.JTextField jTextField_Phone;
    private javax.swing.JTextField jTextField_Roll;
    // End of variables declaration//GEN-END:variables
}
